module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#4cd7f6",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary-fixed-dim": "#bcc7de",
        "on-surface": "#dfe2f1",
        "on-tertiary-fixed": "#2a1700",
        "on-primary-fixed": "#001f26",
        "outline-variant": "#3d494c",
        "tertiary-fixed": "#ffddb8",
        "on-secondary": "#263143",
        "primary-fixed": "#acedff",
        "error": "#ffb4ab",
        "inverse-surface": "#dfe2f1",
        "surface-variant": "#313540",
        "inverse-on-surface": "#2c303b",
        "on-secondary-fixed": "#111c2d",
        "surface-container-lowest": "#0a0e18",
        "surface-dim": "#0f131d",
        "on-secondary-fixed-variant": "#3c475a",
        "primary-fixed-dim": "#4cd7f6",
        "tertiary": "#ffb95f",
        "surface-bright": "#353944",
        "tertiary-container": "#e79400",
        "secondary": "#bcc7de",
        "on-primary-container": "#00424f",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#004e5c",
        "on-secondary-container": "#aeb9d0",
        "on-primary": "#003640",
        "primary": "#4cd7f6",
        "on-error-container": "#ffdad6",
        "primary-container": "#06b6d4",
        "secondary-fixed": "#d8e3fb",
        "on-background": "#dfe2f1",
        "surface": "#0f131d",
        "inverse-primary": "#00687a",
        "surface-container-highest": "#313540",
        "surface-container-high": "#262a35",
        "on-tertiary-container": "#563400",
        "surface-container-low": "#171b26",
        "on-surface-variant": "#bcc9cd",
        "on-tertiary-fixed-variant": "#653e00",
        "on-tertiary": "#472a00",
        "background": "#0f131d",
        "outline": "#869397",
        "surface-container": "#1c1f2a",
        "secondary-container": "#3e495d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-sm": "8px",
        "margin-md": "16px",
        "gutter": "1px",
        "panel-padding": "12px",
        "container-max": "100%",
        "unit": "4px",
        "margin-xs": "4px"
      },
      fontFamily: {
        "body-sm": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["JetBrains Mono"],
        "mono-data": ["JetBrains Mono"]
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "mono-data": ["13px", { "lineHeight": "20px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
