module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "var(--surface-tint)",
        "error-container": "var(--error-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-surface": "var(--on-surface)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "outline-variant": "var(--outline-variant)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-secondary": "var(--on-secondary)",
        "primary-fixed": "var(--primary-fixed)",
        "error": "var(--error)",
        "inverse-surface": "var(--inverse-surface)",
        "surface-variant": "var(--surface-variant)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-dim": "var(--surface-dim)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "tertiary": "var(--tertiary)",
        "surface-bright": "var(--surface-bright)",
        "tertiary-container": "var(--tertiary-container)",
        "secondary": "var(--secondary)",
        "on-primary-container": "var(--on-primary-container)",
        "on-error": "var(--on-error)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-primary": "var(--on-primary)",
        "primary": "var(--primary)",
        "on-error-container": "var(--on-error-container)",
        "primary-container": "var(--primary-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-background": "var(--on-background)",
        "surface": "var(--surface)",
        "inverse-primary": "var(--inverse-primary)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-container-high": "var(--surface-container-high)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "surface-container-low": "var(--surface-container-low)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-tertiary": "var(--on-tertiary)",
        "background": "var(--background)",
        "outline": "var(--outline)",
        "surface-container": "var(--surface-container)",
        "secondary-container": "var(--secondary-container)"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-sm": "8px",
        "margin-md": "16px",
        "gutter": "1px",
        "panel-padding": "12px",
        "container-max": "100%",
        "unit": "4px",
        "margin-xs": "4px"
      },
      fontFamily: {
        "body-sm": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["JetBrains Mono"],
        "mono-data": ["JetBrains Mono"]
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "mono-data": ["13px", { "lineHeight": "20px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
